name: flutter_barrage_example
description: An example project for flutter_barrage.
version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.3.3

  flutter_barrage:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
